fabric_bolt/core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from fabric_bolt.core import views

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.Dashboard.as_view(), name='index'),
    url(r'^hosts/', include('fabric_bolt.hosts.urls')),
    url(r'^web-hooks/', include('fabric_bolt.web_hooks.urls')),
    url(r'^launch-window/', include('fabric_bolt.launch_window.urls')),
    url(r'^projects/', include('fabric_bolt.projects.urls')),
    url(r'^users/', include('fabric_bolt.accounts.urls')),
]

# Serve the static files from django

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
        url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

fabric_bolt/projects/urls.py
from django.conf.urls import url, include
from fabric_bolt import task_runners

from fabric_bolt.projects import views


urlpatterns = [
    url(r'^$', views.ProjectList.as_view(), name='projects_project_list'),

    url(r'^create/$', views.ProjectCreate.as_view(), name='projects_project_create'),

    url(r'^(?P<pk>\w+)/$', views.ProjectDetail.as_view(), name='projects_project_view'),
    url(r'^(?P<pk>\w+)/update/$', views.ProjectUpdate.as_view(), name='projects_project_update'),
    url(r'^(?P<pk>\w+)/delete/$', views.ProjectDelete.as_view(), name='projects_project_delete'),
    url(r'^(?P<pk>\w+)/invalidate-cache/$', views.ProjectInvalidateCache.as_view(), name='projects_project_invalidate_cache'),
    url(r'^(?P<pk>\w+)/copy/$', views.ProjectCopy.as_view(), name='projects_project_copy'),

    url(r'^(?P<project_id>\w+)/configuration/$', views.ProjectConfigurationList.as_view(), name='projects_configuration_list'),
    url(r'^(?P<project_id>\w+)/configuration/create/$', views.ProjectConfigurationCreate.as_view(), name='projects_configuration_create'),
    url(r'^(?P<project_id>\w+)/stage/(?P<stage_id>\d+)/configuration/create/$', views.ProjectConfigurationCreate.as_view(), name='projects_configuration_stage_create'),
    url(r'^(?P<project_id>\w+)/configuration/(?P<pk>\w+)/update/$', views.ProjectConfigurationUpdate.as_view(), name='projects_configuration_update'),
    url(r'^(?P<project_id>\w+)/configuration/(?P<pk>\w+)/delete/$', views.ProjectConfigurationDelete.as_view(), name='projects_configuration_delete'),

    url(r'^(?P<project_id>\w+)/deployment/$', views.ProjectDeploymentList.as_view(), name='projects_deployment_list'),
    url(r'^(?P<project_id>\w+)/stage/(?P<stage_id>\d+)/deployment/create/$', views.DeploymentCreate.as_view(), name='projects_deployment_create'),
    url(r'^(?P<project_id>\w+)/stage/(?P<stage_id>\d+)/deployment/(?P<pk>\d+)/$', views.DeploymentDetail.as_view(), name='projects_deployment_detail'),
    url(r'^(?P<project_id>\w+)/stage/(?P<stage_id>\d+)/deployment/(?P<pk>\d+)/', include(task_runners.backend.get_urls())),

    url(r'^(?P<project_id>\w+)/stage/$', views.ProjectStageList.as_view(), name='projects_stage_list'),
    url(r'^(?P<project_id>\w+)/stage/create/$', views.ProjectStageCreate.as_view(), name='projects_stage_create'),
    url(r'^(?P<project_id>\w+)/stage/(?P<pk>\w+)/$', views.ProjectStageView.as_view(), name='projects_stage_view'),
    url(r'^(?P<project_id>\w+)/stage/(?P<pk>\w+)/update/$', views.ProjectStageUpdate.as_view(), name='projects_stage_update'),
    url(r'^(?P<project_id>\w+)/stage/(?P<pk>\w+)/get-tasks-ajax/$', views.ProjectStageTasksAjax.as_view(), name='projects_stage_tasks_ajax'),
    url(r'^(?P<project_id>\w+)/stage/(?P<pk>\w+)/delete/$', views.ProjectStageDelete.as_view(), name='projects_stage_delete'),

    url(r'^(?P<project_id>\w+)/stage/(?P<stage_id>\w+)/configuration/$', views.StageConfigurationList.as_view(), name='projects_stage_configuration_list'),
    url(r'^(?P<project_id>\w+)/stage/(?P<stage_id>\w+)/deployment/$', views.StageDeploymentList.as_view(), name='projects_stage_deployment_list'),
    url(r'^(?P<project_id>\w+)/stage/(?P<stage_id>\w+)/host/(?P<host_id>\w+)/map/$', views.ProjectStageMapHost.as_view(), name='projects_stage_maphost'),
    url(r'^(?P<project_id>\w+)/stage/(?P<stage_id>\w+)/host/(?P<host_id>\w+)/unmap/$', views.ProjectStageUnmapHost.as_view(), name='projects_stage_unmaphost'),
]

fabric_bolt/projects/models.py
import operator

import ansiconv
from django.core.urlresolvers import reverse
from django.db.models import Count, Sum, F
from django.db import models
from django.db.models import Q
from django.conf import settings

from fabric_bolt.core.mixins.models import TrackingFields
from fabric_bolt.projects.model_managers import ActiveManager, ActiveDeploymentManager
from fabric_bolt.hosts.models import SSHConfig


class CF(F):
    ADD = '||'


class Project(TrackingFields):
    """Model for a project (pretty obvious)

    Keeps track of the stages and general configurations for deployments"""

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    use_repo_fabfile = models.BooleanField(default=False, verbose_name='Use repo\'s fabfile?',
                                           help_text='If no, use the default fabfile.')
    repo_url = models.CharField(max_length=200, null=True, blank=True, help_text='Currently only git repos are supported.')
    fabfile_requirements = models.TextField(null=True, blank=True, help_text='Pip requirements to install for fabfile. '
                                                                             'Enter one requirement per line.')

    # Managers
    objects = models.Manager()
    active_records = ActiveManager()
    # End Managers

    def project_configurations(self):
        return Configuration.objects.filter(project_id=self.pk, stage__isnull=True)

    def __unicode__(self):
        return self.name

    def get_stages(self):
        """Utility function that returns the stages on a specific project"""

        return Stage.active_records.filter(project=self)

    def get_absolute_url(self):
        """Let's see the project detail page now."""

        return reverse('projects_project_view', args=(self.pk,))

    def web_hooks(self, include_global=True):
        """Get all web hooks for this project. Includes global hooks."""
        from fabric_bolt.web_hooks.models import Hook
        ors = [Q(project=self)]

        if include_global:
            ors.append(Q(project=None))

        hooks = Hook.objects.filter(reduce(operator.or_, ors))

        return hooks

    def get_deployment_count(self):
        """Utility function to get the number of deployments a given project has"""

        ret = self.stage_set.annotate(num_deployments=Count('deployment')).aggregate(total_deployments=Sum('num_deployments'))
        return ret['total_deployments']


class Stage(TrackingFields):
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=255)
    hosts = models.ManyToManyField('hosts.Host')

    # Managers
    objects = models.Manager()
    active_records = ActiveManager()
    # End Managers

    def __unicode__(self):
        return self.name

    def stage_configurations(self):
        """Helper function that returns the stage specific configurations"""

        return Configuration.objects.filter(stage=self)

    def get_absolute_url(self):
        """Stages are show on a project page so that's where we're sending you to see them"""

        return self.project.get_absolute_url()

    @property
    def web_hooks(self):
        """Get web hooks from the project"""

        return self.project.web_hooks()

    def get_queryset_configurations(self, **kwargs):
        """
        Really we just want to do a simple SQL statement like this (but oh the ORM):

        SELECT Distinct(Coalesce(stage.key, project.key)) AS key,
        (CASE WHEN stage.key IS NOT null THEN stage.data_type ELSE project.data_type END) AS data_type,
        (CASE WHEN stage.key IS NOT null THEN stage.value ELSE project.value END) AS value,
        (CASE WHEN stage.key IS NOT null THEN stage.value_number ELSE project.value_number END) AS value_number,
        (CASE WHEN stage.key IS NOT null THEN stage.value_boolean ELSE project.value_boolean END) AS value_boolean,
        (CASE WHEN stage.key IS NOT null THEN stage.prompt_me_for_input ELSE project.prompt_me_for_input END) AS prompt_me_for_input,
        (CASE WHEN stage.key IS NOT null THEN stage.sensitive_value ELSE project.sensitive_value END) AS sensitive_value
        FROM projects_configuration AS project
        LEFT JOIN projects_configuration AS stage ON stage.project_id = project.project_id
            AND project.key = stage.key AND stage.stage_id = STAGE_ID_HERE
        WHERE project.project_id = PROJECT_ID_HERE AND (project.stage_id is null OR project.stage_id = STAGE_ID_HERE)
        """
        queryset_list = []
        current_configs = []

        # Create stage specific configurations dictionary
        for stage in self.stage_configurations().filter(**kwargs):
            queryset_list.append(stage)
            current_configs.append(stage.key)

        for project in self.project.project_configurations().filter(**kwargs):
            if not project.key in current_configs:
                queryset_list.append(project)
                current_configs.append(project.key)

        return queryset_list

    def get_configurations(self):
        """
        Generates a dictionary that's made up of the configurations on the project.
        Any configurations on a project that are duplicated on a stage, the stage configuration will take precedence.
        """

        project_configurations_dictionary = {}
        project_configurations = self.project.project_configurations()

        # Create project specific configurations dictionary
        for config in project_configurations:
            project_configurations_dictionary[config.key] = config

        stage_configurations_dictionary = {}
        stage_configurations = self.stage_configurations()

        # Create stage specific configurations dictionary
        for s in stage_configurations:
            stage_configurations_dictionary[s.key] = s

        # override project specific configuration with the ones in the stage if they are there
        project_configurations_dictionary.update(stage_configurations_dictionary)

        # Return the updated configurations
        return project_configurations_dictionary


class Configuration(TrackingFields):
    """Configurations can be on a project or a specific stage.

    If a configuration value is found on both a project and a stage then the stage's configuration value will be the
    one used.

    These are key:value pairs that are pumped into the fab script via the command line. Inside your fab script you'll
    have access to env.key (env.server_ip, env.port_number, etc).
    """

    BOOLEAN_TYPE = 'boolean'
    NUMBER_TYPE = 'number'
    STRING_TYPE = 'string'
    SSH_KEY_TYPE = 'ssh_key'

    DATA_TYPES = ((BOOLEAN_TYPE, 'Boolean'), (NUMBER_TYPE, 'Number'), (STRING_TYPE, 'String'), (SSH_KEY_TYPE, 'SSH Key'))

    project = models.ForeignKey(Project)
    stage = models.ForeignKey(Stage, null=True, blank=True)

    key = models.CharField(max_length=255)
    value = models.CharField(max_length=500, null=True, blank=True)
    value_number = models.FloatField(verbose_name='Value', null=True, blank=True, default=0)
    value_boolean = models.BooleanField(verbose_name='Value', default=False)
    value_ssh_key = models.ForeignKey(SSHConfig, verbose_name='Value', blank=True, null=True)
    data_type = models.CharField(choices=DATA_TYPES, null=True, blank=True, max_length=10, default=STRING_TYPE, verbose_name='Type')

    task_name = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text='The name of the task this argument should be used on.'
    )

    prompt_me_for_input = models.BooleanField(
        default=False,
        help_text='When deploying you will be prompted for this value.'
    )
    sensitive_value = models.BooleanField(
        default=False,
        help_text='Password or other value that should not be stored in the logs.'
    )
    task_argument = models.BooleanField(
        default=False,
        help_text='"Configuration" should be passed as a task argument rather than set on env.'
    )

    # Managers
    objects = models.Manager()
    active_records = ActiveManager()
    # End Managers

    def __unicode__(self):
        return u'{}: {}'.format(self.key, self.value)

    def get_absolute_url(self):
        """Determine where I am coming from and where I am going"""

        # Determine if this configuration is on a stage
        if self.stage:
            # Stage specific configurations go back to the stage view
            url = reverse('projects_stage_view', args=(self.project.pk, self.stage.pk))
        else:
            # Project specific configurations go back to the project page
            url = self.project.get_absolute_url()

        return url

    def get_value(self):
        """Determine the proper value based on the data_type"""

        if self.data_type == self.BOOLEAN_TYPE:
            return self.value_boolean
        elif self.data_type == self.NUMBER_TYPE:
            return self.value_number
        elif self.data_type == self.SSH_KEY_TYPE:
            return self.value_ssh_key.private_key_file._get_path()
        else:
            return self.value

    def set_value(self, value):
        """Determine the proper value based on the data_type"""

        if self.data_type == self.BOOLEAN_TYPE:
            self.value_boolean = bool(value)
        elif self.data_type == self.NUMBER_TYPE:
            self.value_number = float(value)
        else:
            self.value = value

    def get_display_value(self):
        if self.sensitive_value:
            return "******"

        return self.get_value()


class Deployment(TrackingFields):
    """Archival record of an actual deployment, tracks:

    - Which user ran it
    - Stage it was on
    - Status
    - Fabric task that was run
    - The configuration used

    - Among other miscellaneous things
    """

    PENDING = 'pending'
    FAILED = 'failed'
    SUCCESS = 'success'

fabric_bolt/projects/templates/projects/configuration_create.html
{% extends 'projects/configuration_update.html' %}
{% load crispy_forms_tags %}

{% block project_breadcrumb_links %}
    <li><a href="{% url 'projects_project_view' project.pk %}">{{ project.name }}</a></li>
    <li><a href="{% url 'projects_configuration_list' project.pk %}">Configurations</a></li>
    <li class="active">Create Configuration</li>
{% endblock project_breadcrumb_links %}

{% block action %}Add New{% endblock %}

fabric_bolt/projects/templates/projects/configuration_list.html
{% extends 'projects/project_base.html' %}
{% load crispy_forms_tags %}
{% load sekizai_tags %}
{% load render_table from django_tables2 %}

{% block project_breadcrumb_links %}
    <li><a href="{% url 'projects_project_view' project.pk %}">{{ project.name }}</a></li>
    <li class="active">Configurations</li>
{% endblock project_breadcrumb_links %}

{% block content %}

    <h1>Project Configuration
        <i class="glyphicon glyphicon-info-sign small" data-toggle="tooltip" data-delay="{ 'show': 300, 'hide': 0 }"
                           data-original-title="Configurations added here will be added to fab's env variable"></i>
        <a href="{% url 'projects_configuration_create' project.pk %}" class="btn btn-default btn-sm pull-right">
            <i class="glyphicon glyphicon-plus-sign"></i> Add Configuration
        </a>
    </h1><br/>
    {% render_table table %}

{% endblock content %}

fabric_bolt/projects/templates/projects/configuration_stage_list.html
{% extends 'projects/stage_base.html' %}
{% load crispy_forms_tags %}
{% load sekizai_tags %}
{% load render_table from django_tables2 %}

{% block stage_breadcrumb_links %}
    <li><a href="{% url 'projects_stage_view' project.pk stage.pk %}">{{ stage.name }}</a></li>
    <li class="active">Configuration</li>
{% endblock stage_breadcrumb_links %}

{% block content %}

    <h1>Stage Configuration
        <i class="glyphicon glyphicon-info-sign small" data-toggle="tooltip" data-delay="{ 'show': 300, 'hide': 0 }"
                           data-original-title="Configurations added here will be added to fab's env variable and will override whatever is in the project configuration."></i>
        <a href="{% url 'projects_configuration_stage_create' project.pk stage.pk %}" class="btn btn-default btn-sm pull-right">
            <i class="glyphicon glyphicon-plus-sign"></i> Add Stage Configuration
        </a>
    </h1><br/>
    {% render_table table %}

{% endblock content %}

fabric_bolt/projects/templates/projects/configuration_update.html
{% extends 'projects/project_base.html' %}
{% load crispy_forms_tags %}
{% load sekizai_tags %}

{% block project_breadcrumb_links %}
    <li><a href="{% url 'projects_project_view' project.pk %}">{{ project.name }}</a></li>
    <li><a href="{% url 'projects_configuration_list' project.pk %}">Configurations</a></li>
    <li class="active">Update Configuration</li>
{% endblock project_breadcrumb_links %}

{% block content %}
    <h1>{% block action %}Update{% endblock action %} Configuration</h1><br/>
    <style>
        #div_id_value_boolean, #div_id_value_number, #div_id_value_ssh_key {
            display: none;
        }
    </style>
    {% crispy form %}

    {% addtoblock 'js' %}
        <script>
            function set_data_type_field(){
                var data_type = $('#id_data_type').val();
                $('#div_id_value_boolean, #div_id_value, #div_id_value_number, #div_id_value_ssh_key').hide();
                $('#id_key').attr('readonly', false);
                if(data_type == 'boolean'){
                    $('#div_id_value_boolean').show();
                }else if(data_type == 'number'){
                    $('#div_id_value_number').show();
                }else if(data_type == 'ssh_key'){
                    $('#div_id_value_ssh_key').show();
                    $('#id_key').val('key_filename').attr('readonly', true);
                }else{
                    $('#div_id_value').show();
                }
            }

            function show_hide_task_name_field(){
                var task_argument = $('#id_task_argument').is(':checked');
                if(task_argument){
                    $('#div_id_task_name').show();
                }else{
                    $('#div_id_task_name').hide();
                }
            }

            $(function(){
                set_data_type_field();
                $('#id_data_type').change(set_data_type_field);

                show_hide_task_name_field();
                $('#id_task_argument').change(show_hide_task_name_field);
            });
        </script>
    {% endaddtoblock %}
{% endblock %}

fabric_bolt/projects/templates/projects/deployment_form.html
{% extends 'projects/stage_base.html' %}
{% load crispy_forms_tags %}


{% block stage_breadcrumb_links %}
    <li><a href="{% url 'projects_stage_view' stage.project.pk stage.pk %}">{{ stage.name }}</a></li>
    <li class="active">New Deployment</li>
{% endblock stage_breadcrumb_links %}

{% block content %}
    <h1>Deploy</h1><br/>
    <div class="row">
        <div class="col-md-6">
            {% crispy form %}
        </div>
        <div class="col-md-6">
            <div class="well">
                <legend>Stats</legend>
                <dl class="dl-horizontal">
                    <dt>Project</dt>
                    <dd>{{ stage.project.name }}</dd>
                    <dt>Stage</dt>
                    <dd>{{ stage.name }}</dd>
                    <dt>Task</dt>
                    <dd>{{ task_name }}</dd>
                    <dt>Task Description</dt>
                    <dd>{{ task_description|linebreaksbr }}</dd>
                </dl>
            </div>

            <div class="well">
                <legend>Configurations (env)</legend>
                <dl class="dl-horizontal">
                    {% for config in configs %}
                        <dt>{{ config.key }}</dt>
                        <dd>{{ config.get_display_value }}</dd>
                    {% empty %}
                        <dt>Configs</dt>
                        <dd>None Set</dd>
                    {% endfor %}
                </dl>
            </div>
        </div>
    </div>

{% endblock content %}

fabric_bolt/projects/templates/projects/deployment_list.html
{% extends 'projects/project_base.html' %}
{% load crispy_forms_tags %}
{% load sekizai_tags %}
{% load render_table from django_tables2 %}

{% block project_breadcrumb_links %}
    <li><a href="{% url 'projects_project_view' project.pk %}">{{ project.name }}</a></li>
    <li class="active">Deployments</li>
{% endblock project_breadcrumb_links %}

{% block content %}

    <h1>Project Deployments
        <i class="glyphicon glyphicon-info-sign small" data-toggle="tooltip" data-delay="{ 'show': 300, 'hide': 0 }"
                           data-original-title="See what was shipped out when, and the status of each attempt."></i>
    </h1><br/>
    {% render_table table %}

{% endblock content %}

fabric_bolt/projects/templates/projects/historian_detail.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'projects_project_list' %}">Projects</a></li>
        <li class="active">{{ object.name }}</li>
    </ol>
{% endblock breadcrumb %}

{% block content %}
    <div class="row">
        <h1 style="margin-bottom:30px;" class="col-lg-12">Project {{ object.name }}
        </h1>
    </div>

    <div class="row">
        <div class="col-md-7">
            <div class="well well-sm">
                <div>
                    Description: {{ object.description }}
                </div>
                <div>Deployments: {{ object.get_deployment_count }}</div>
                <div></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4>
                        Recent Deployments
                        <i class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-delay="{ 'show': 300, 'hide': 0 }"
                           data-original-title="See what was shipped out when, and the status of each attempt."></i>
                    </h4>
                </div>

                <div class="panel-body">
                    {% render_table deployment_table %}
                </div>

            </div>
        </div>
    </div>

{% endblock content %}

fabric_bolt/projects/templates/projects/project_confirm_delete.html
{% extends 'projects/project_base.html' %}

{% block project_breadcrumb_links %}
    <li><a href="{% url 'projects_project_view' project.pk %}">{{ project.name }}</a></li>
    <li class="active">Delete</li>
{% endblock project_breadcrumb_links %}

{% block content %}
    <h1>Delete Project?</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete the project {{ object }}?</p>
        <input type="submit" value="Yes, I'm Sure." class="btn btn-danger"/>
    </form>
{% endblock content %}

fabric_bolt/projects/templates/projects/project_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'projects_project_list' %}">Projects</a></li>
        <li class="active">Add Project</li>
    </ol>
{% endblock breadcrumb %}

{% block content %}
    <h1>Add New Project</h1>

    {% crispy form %}

{% endblock %}

fabric_bolt/projects/templates/projects/project_detail.html
{% extends 'projects/project_base.html' %}
{% load render_table from django_tables2 %}


{% block content %}
    <div class="row">
        <h1 style="margin-bottom:30px;" class="col-lg-12">Project {{ object.name }}
            <span class="pull-right">
                <a class="btn btn-primary" href="{% url 'projects_project_update' object.pk %}">Edit Project</a>
                <a class="btn btn-danger" href="{% url 'projects_project_delete' object.pk %}">Delete Project</a>
            </span>
        </h1>
    </div>

    <div class="row">
        <div class="col-md-7">
            <div class="well well-sm">
                <div>
                    Description: {{ object.description }}
                </div>
                <div>Deployments: {{ object.get_deployment_count }}</div>
                <div><a href="{% url 'projects_project_invalidate_cache' object.pk %}">Invalidate tasks cache</a></div>
            </div>
        </div>

        <div class="col-md-5">
            <div class="well well-sm">
                <div class="list-group">
                    {% for stage in stages %}
                        <a href="{% url 'projects_stage_view' object.pk stage.pk %}" class="list-group-item">
                            <span class="badge" data-toggle="tooltip" data-delay="{ 'show': 300, 'hide': 0 }" data-original-title="Number of configurations">{{ stage.stage_configurations.count }}</span>
                            {{ stage.name }}
                        </a>
                    {% empty %}
                        <div class="list-group-item">No stage configured yet</div>
                    {% endfor %}
                </div>

                <div>
                    <a class="btn btn-default btn-sm" href="{% url 'projects_stage_create' object.pk %}">
                        <i class="glyphicon glyphicon-plus-sign"></i>
                        Add Stage
                    </a>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

fabric_bolt/projects/templates/projects/project_update.html
{% extends 'projects/project_base.html' %}
{% load crispy_forms_tags %}

{% block project_breadcrumb_links %}
    <li><a href="{% url 'projects_project_view' project.pk %}">{{ project.name }}</a></li>
    <li class="active">Update</li>
{% endblock project_breadcrumb_links %}

{% block content %}
    <h1>Update Project</h1>
    {% crispy form %}
{% endblock %}

fabric_bolt/projects/templates/projects/stage_base.html
{% extends 'base.html' %}
{% load activeurl %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'projects_project_list' %}">Projects</a></li>
        <li><a href="{% url 'projects_project_view' project.pk %}">{{ project.name }}</a></li>
        <li><a href="{% url 'projects_stage_list' project.pk %}">Stages</a></li>
        {% block stage_breadcrumb_links %}
            <li class="active">{{ stage.name }}</li>
        {% endblock stage_breadcrumb_links %}
    </ol>
{% endblock breadcrumb %}

{% block wrapper-class %}col-md-9{% endblock wrapper-class %}

{% block sidebar %}
    <div class="col-md-3" style="margin-top: 25px;">
        {% activeurl menu="no" %}
            <ul class="nav nav-pills nav-stacked">
                <li>
                    <a href="{% url 'projects_project_view' project.pk %}">
                        Project Dashboard &#160;&#160;&#160;<i class="glyphicon glyphicon-arrow-up"></i>
                    </a>
                </li>
                <li>
                    <a href="{% url 'projects_stage_view' project.pk stage.pk %}">
                        <i class="glyphicon glyphicon-dashboard"></i> &#160;&#160;&#160;Stage
                    </a>
                </li>
                <li>
                    <a href="{% url 'projects_stage_configuration_list' project.pk stage.pk %}">
                        <i class="glyphicon glyphicon-cog"></i> &#160;&#160;&#160;Configuration
                    </a>
                </li>
                <li>
                    <a href="{% url 'projects_stage_deployment_list' project.pk stage.pk %}">
                        <i class="glyphicon glyphicon-play"></i> &#160;&#160;&#160;Deployments
                    </a>
                </li>
            </ul>
        {% endactiveurl %}
    </div>
{% endblock %}

fabric_bolt/projects/templates/projects/stage_update.html
{% extends 'projects/stage_base.html' %}
{% load crispy_forms_tags %}

{% block stage_breadcrumb_links %}
    <li><a href="{% url 'projects_stage_view' project.pk object.pk %}">{{ object.name }}</a></li>
    <li class="active">Update</li>
{% endblock stage_breadcrumb_links %}

{% block content %}
    <h1>Stage Update</h1>

    {% crispy form %}

{% endblock %}